name: 'Build target'
description: 'Helper for workflows/test-build.yml'
inputs:
  compiler:
    description: 'C++ compiler executable'
    required: true
  stdlib:
    description: 'C++ standard library to use (libstdc++ or libc++)'
    required: false
    default: libstdc++

runs:
  using: 'composite'
  steps:
    - shell: bash
      working-directory: ${{ matrix.TARGET.directory }}
      env:
        CXX: ${{ inputs.compiler }}
        USE_LIBCXX: ${{ inputs.stdlib == 'libc++' && 'TRUE' || 'FALSE' }}
      run: |
        echo
        echo '::group::Compiler version'
        $CXX --version
        echo '::endgroup::'
        echo
        make -j4 DISABLE_SANITIZERS=TRUE build/release/${{ matrix.TARGET.name }} build/debug/${{ matrix.TARGET.name }} build/fast/${{ matrix.TARGET.name }}
