#!/bin/bash
set -euo pipefail

usage() {
  echo "Usage: aoc [day] [-t|--gdb] [-q] [-d|-f] [-s <binary suffix>] [-w] [-e [example number]|-i <input file name>]"
}

AOC_ROOT="$(git rev-parse --show-toplevel)"
# shellcheck source=../lib.sh
source "$AOC_ROOT/tools/lib.sh"
# shellcheck source=../cli.sh
source "$AOC_ROOT/tools/cli.sh"
# cd to the base directory for this year
cd -- "$AOC_ROOT/$AOC_YEAR"

setup_help

memory_limit=4G
prefix_args=()
write_answer=n
use_gdb=n

init_day_args
init_input_args
init_target_args
init_make_args

first_iter=y
while [[ $# -gt 0 ]]; do
  case $1 in
    -t|--time)
      prefix_args=(/usr/bin/time)
      shift
      ;;
    -m|--memory-limit)
      memory_limit=$2
      shift
      shift
      ;;
    -w|--write-answer)
      write_answer=y
      shift
      ;;
    --gdb)
      use_gdb=y
      prefix_args=(gdb --args)
      # run directly in the terminal
      memory_limit=none
      # detect_leaks=0:   Both gdb and LeakSanitizer use ptrace, but only one
      #                   process can attach at a time
      # abort_on_error=1: Break into gdb after a memory error is detected
      ASAN_OPTIONS=${ASAN_OPTIONS:+${ASAN_OPTIONS}:}detect_leaks=0:abort_on_error=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      shift_count=0
      if handle_input_arg "$@"; then
        shift "$shift_count"
      elif handle_target_arg "$@"; then
        shift "$shift_count"
      elif handle_make_arg "$@"; then
        shift "$shift_count"
      else
        echo "Error: unrecognized option '$1'"
        usage
        exit 1
      fi
      ;;
    *)
      handle_day_arg "$@"
      # we either consumed the day number or exited with an error
      shift
      ;;
  esac
  first_iter=n
done

finalize_day_args
finalize_input_args
finalize_target_args
finalize_make_args

# print a stacktrace on UBSan errors by default
export UBSAN_OPTIONS=${UBSAN_OPTIONS:-print_stacktrace=1}
# have ASan print a backtrace when an assertion fails (which triggers an abort)
export ASAN_OPTIONS="${ASAN_OPTIONS:+${ASAN_OPTIONS}:}handle_abort=1"

if [[ $write_answer != y ]]; then
  echo "Day ${day#0}$suffix:"
fi
args=("${prefix_args[@]}" "$binary" "$input_path")

# run on the specified input
exit_code=0
if [[ $write_answer == y ]]; then
  output="answer_tests/${input_path#input/}"
  out_dir="$(dirname "$output")"
  mkdir -p "$out_dir"
  tmp_output="$(mktemp -p "$out_dir")"
  echo "Day ${day#0}:" > "$tmp_output"
  "${args[@]}" >> "$tmp_output" || exit_code=$?
  cat "$tmp_output"
  if [[ $exit_code -eq 0 ]]; then
    mv "$tmp_output" "$output" || true
  else
    rm -f "$tmp_output" || true
  fi
elif [[ $memory_limit == none ]]; then
  "${args[@]}" || exit_code=$?
else
  # limit memory usage using a systemd transient unit
  systemctl --quiet --user is-failed aoc.service && systemctl --user reset-failed aoc.service
  # explicitly stop the unit on SIGINT, as systemd-run doesn't seem to handle
  # it if any of the standard streams are redirected
  trap 'systemctl --quiet --user is-active aoc.service && systemctl --quiet --user stop aoc.service; exit 130' INT
  systemd-run --unit=aoc.service --quiet --user --pipe --wait --pty --same-dir -p MemoryMax="$memory_limit" -p MemorySwapMax=0 -E ASAN_OPTIONS -E UBSAN_OPTIONS "${args[@]}" || exit_code=$?
  trap - INT
  if systemctl --quiet --user is-failed aoc.service; then
    result=$(systemctl --user show -p Result aoc | sed -ne 's/^Result=//p')
    exit_code=$(systemctl --user show -p ExecMainStatus aoc | sed -ne 's/^ExecMainStatus=//p')
    if [[ $result == core-dump ]]; then
      (( exit_code += 128 ))
    fi
    if [[ $result == oom-kill ]]; then
      >&2 echo "ERROR: ran out of memory (limited to $memory_limit)"
    fi
    systemctl --user reset-failed aoc.service
  fi
fi
exit "$exit_code"
