#!/bin/bash
set -euo pipefail

AOC_ROOT="$(git rev-parse --show-toplevel)"
# shellcheck source=../lib.sh
source "$AOC_ROOT/tools/lib.sh"

sources=()
headers=()
tool_args=()
iwyu_args=()
while [[ $# -gt 0 ]]; do
  arg=$1
  shift
  if [[ $arg == -- ]]; then
    break;
  fi
  case $arg in
    *.cpp)
      sources+=("$arg")
      ;;
    *.h|*.hpp)
      headers+=("$arg")
      ;;
    --help)
      iwyu-tool --help
      printf '\n\n'
      include-what-you-use --help
      exit
      ;;
    -Xiwyu)
      iwyu_args+=("$arg" "$1")
      shift 1
      ;;
    --verbose=*)
      # pass directly to include-what-you-use
      iwyu_args+=(-Xiwyu "$arg")
      ;;
    *)
      tool_args+=("$arg")
      ;;
  esac
done
function run_iwyu-tool () {
  iwyu-tool "$@"
}
if [[ ${#headers[@]} -eq 0 ]]; then
  # for some reason, absolute paths don't work for aoc_lib
  # * paths appear to be relative to the "directory" entry in compile_commands.json
  # * -Xiwyu --check_also handles globs
  headers=("$AOC_ROOT/$AOC_YEAR/src/*.hpp" '../aoc_lib/src/*.hpp' '../aoc_lib/src/*/*.hpp')
fi
if [[ ${#sources[@]} -eq 0 ]]; then
  sources=("$AOC_ROOT/$AOC_YEAR"/src/*.cpp)
  tool_args+=(-j"$(nproc)" -o clang)
  function run_iwyu-tool () {
    iwyu-tool "$@" | { grep -v ' are correct' || true; } | LC_COLLATE=C sort -t: -k1,1 -k2,2n -k3,3n -k4 -u && echo 'all #includes/fwd-decls are correct'
  }
fi
for f in "${headers[@]}"; do
  iwyu_args+=(-Xiwyu "--check_also=$f")
done
# add remaining arguments to include-what-you-use args
iwyu_args+=("$@")

run_iwyu-tool -p "$AOC_ROOT/compile_commands.json" "${tool_args[@]}" "${sources[@]}" -- --no-warnings -Xiwyu --error -Xiwyu --quoted_includes_first -Xiwyu --max_line_length=300 -Xiwyu --mapping_file="$TOOLS_DIR/cpp/iwyu_mappings.imp" -resource-dir "$(clang -print-resource-dir)" "${iwyu_args[@]}"
