#!/bin/bash
set -euo pipefail

AOC_ROOT="$(git rev-parse --show-toplevel)"
# shellcheck source=../lib.sh
source "$AOC_ROOT/tools/lib.sh"

sources=()
tool_args=()
iwyu_args=()
while [[ $# -gt 0 ]]; do
  if [[ $1 == -- ]]; then
    break;
  fi
  case $1 in
    *.cpp)
      sources+=("$1")
      shift
      ;;
    *.h|*.hpp)
      iwyu_args+=(-Xiwyu --check_also="$1")
      shift
      ;;
    --help)
      iwyu-tool --help
      printf '\n\n'
      include-what-you-use --help
      exit
      ;;
    -Xiwyu)
      iwyu_args+=("$1" "$2")
      shift 2
      ;;
    --verbose=*)
      # pass directly to include-what-you-use
      iwyu_args+=(-Xiwyu "$1")
      shift
      ;;
    *)
      tool_args+=("$1")
      shift
      ;;
  esac
done
# add remaining arguments to include-what-you-use args
iwyu_args+=("$@")

iwyu-tool -p "../compile_commands_$AOC_YEAR.json" "${tool_args[@]}" "${sources[@]}" -- --no-warnings -Xiwyu --quoted_includes_first -Xiwyu --max_line_length=300 -Xiwyu --mapping_file="$TOOLS_DIR/cpp/iwyu_mappings.imp" -resource-dir "$(clang -print-resource-dir)" "${iwyu_args[@]}"
