name: Run answer tests

on: [push]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    name: Get changed files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          json: true

      # reference: https://stackoverflow.com/a/65094398
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: python $GITHUB_WORKSPACE/.github/workflows/gen_matrix.py "${{ steps.changed-files.outputs.all_changed_files }}" $GITHUB_OUTPUT "day"

    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}

  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix
    if: ${{ needs.setup-matrix.outputs.matrix-combinations != '{}' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install compiler
        run: |
          sudo apt-get -qq -y update
          if [[ ${{ matrix.compiler }} == clang++ ]]; then
            sudo apt-get -qq -y install clang
          else
            sudo apt-get -qq -y install g++
          fi

      - name: Build targets
        run: |
          cd ${{ matrix.directory }}
          if [[ -e run_answer_tests.sh ]]; then
            make -j2 CXX=${{ matrix.compiler }} build/release/${{ matrix.target }}
          fi

      - name: Run answer tests
        timeout-minutes: 2
        run: |
          cd ${{ matrix.directory }}
          if [[ -e run_answer_tests.sh ]]; then
            ./run_answer_tests.sh ${{ matrix.target }}
          fi
