name: Run answer tests

on: [push, pull_request]

jobs:
  setup-matrix:
    uses: ./.github/workflows/generate-matrix.yml
    with:
      mode: answer

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      ubuntu-version: 22.04
      llvm-version: 17

  matrix-job:
    runs-on: ubuntu-latest
    needs: [setup-matrix, docker-build]
    if: ${{ needs.setup-matrix.outputs.targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        TARGET: ${{ fromJson(needs.setup-matrix.outputs.targets) }}
    container: ${{ needs.docker-build.outputs.image }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.TARGET.directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Mark git checkout as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run answer tests (clang++)
        timeout-minutes: 2
        run: |
          export CXX=clang++ USE_LIBCXX=FALSE
          echo '::group::make output'
          $CXX --version
          make --silent clean
          make build/release/${{ matrix.TARGET.name }}
          echo '::endgroup::'

          ./run_answer_tests.sh ${{ matrix.TARGET.name }}

      - name: Run answer tests (g++)
        timeout-minutes: 2
        if: always()
        run: |
          export CXX=g++ USE_LIBCXX=FALSE
          echo '::group::make output'
          $CXX --version
          make --silent clean
          make build/release/${{ matrix.TARGET.name }}
          echo '::endgroup::'

          ./run_answer_tests.sh ${{ matrix.TARGET.name }}

      - name: Run answer tests (clang++-17, libc++)
        timeout-minutes: 2
        if: always()
        run: |
          export CXX=clang++-17 USE_LIBCXX=TRUE
          echo '::group::make output'
          $CXX --version
          make --silent clean
          make build/release/${{ matrix.TARGET.name }}
          echo '::endgroup::'

          ./run_answer_tests.sh ${{ matrix.TARGET.name }}
