name: Test building C++ targets

on: [push, pull_request]

jobs:
  setup-matrix:
    uses: ./.github/workflows/generate-matrix.yml
    with:
      mode: build

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      ubuntu-version: 24.04
      gcc-versions: 13
      llvm-versions: '15,17'

  matrix-job:
    runs-on: ubuntu-24.04
    needs: [setup-matrix, docker-build]
    if: ${{ needs.setup-matrix.outputs.targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        TARGET: ${{ fromJson(needs.setup-matrix.outputs.targets) }}
    container: ${{ needs.docker-build.outputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build target (clang++)
        id: clang
        uses: ./.github/actions/build-action
        with:
          compiler: clang++-15

      - name: Build target (g++)
        id: gcc
        # ignore failures in the previous step
        if: success() || steps.clang.conclusion == 'failure'
        uses: ./.github/actions/build-action
        with:
          compiler: g++-13

      - name: Build target (clang++-17, libc++)
        # ignore failures in the previous two steps
        if: success() || steps.clang.conclusion == 'failure' || steps.gcc.conclusion == 'failure'
        uses: ./.github/actions/build-action
        with:
          compiler: clang++-17
          stdlib: libc++
