name: Test building C++ targets

on: [push, pull_request]

jobs:
  setup-matrix:
    uses: ./.github/workflows/generate-matrix.yml
    with:
      mode: build

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      ubuntu-version: 22.04
      llvm-version: 17

  matrix-job:
    runs-on: ubuntu-latest
    needs: [setup-matrix, docker-build]
    if: ${{ needs.setup-matrix.outputs.targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        TARGET: ${{ fromJson(needs.setup-matrix.outputs.targets) }}
    container: ${{ needs.docker-build.outputs.image }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.TARGET.directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build target (clang++)
        run: |
          export CXX=clang++ USE_LIBCXX=FALSE
          $CXX --version
          make --silent clean
          make -j4 DISABLE_SANITIZERS=TRUE build/release/${{ matrix.TARGET.name }} build/debug/${{ matrix.TARGET.name }} build/fast/${{ matrix.TARGET.name }}

      - name: Build target (g++)
        if: always()
        run: |
          export CXX=g++ USE_LIBCXX=FALSE
          $CXX --version
          make --silent clean
          make -j4 DISABLE_SANITIZERS=TRUE build/release/${{ matrix.TARGET.name }} build/debug/${{ matrix.TARGET.name }} build/fast/${{ matrix.TARGET.name }}

      - name: Build target (clang++-17, libc++)
        if: always()
        run: |
          export CXX=clang++-17 USE_LIBCXX=TRUE
          $CXX --version
          make --silent clean
          make -j4 DISABLE_SANITIZERS=TRUE build/release/${{ matrix.TARGET.name }} build/debug/${{ matrix.TARGET.name }} build/fast/${{ matrix.TARGET.name }}
