name: Run unit tests

on: [push, pull_request]

jobs:
  setup-matrix:
    uses: ./.github/workflows/generate-matrix.yml
    with:
      mode: unit

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    if: ${{ !needs.setup-matrix.outputs.empty }}
    permissions:
      packages: write
    with:
      ubuntu-version: 22.04
      llvm-version: 17

  matrix-job:
    runs-on: ubuntu-latest
    needs: [setup-matrix, docker-build]
    if: ${{ !needs.setup-matrix.outputs.empty }}
    strategy:
      fail-fast: false
      matrix:
        TARGET: ${{ fromJson(needs.setup-matrix.outputs.targets) }}
        BUILD_CONFIG: ${{ fromJson(needs.setup-matrix.outputs.build-configs) }}
    container: ${{ needs.docker-build.outputs.image }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.TARGET.directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build test
        run: |
          if [[ ${{ matrix.BUILD_CONFIG.stdlib }} == libc++ ]]; then
            export USE_LIBCXX=TRUE
          fi
          ${{ matrix.BUILD_CONFIG.compiler }} --version
          make CXX=${{ matrix.BUILD_CONFIG.compiler }} build/debug/${{ matrix.TARGET.name }}

      - name: Run test
        run: make CXX=${{ matrix.BUILD_CONFIG.compiler }} ${{ matrix.TARGET.name }}
